[project]
name = "project-name"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "turtwig",
]

[tool.uv.sources]
turtwig = { git = "https://github.com/UWA-Medical-Physics-Research-Group/turtwig" }